name: Deploy Laravel App (FTPS)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Detect composer changes
        id: check_composer
        run: |
          if git diff --name-only HEAD^ HEAD | grep -E 'composer.json|composer.lock'; then
            echo "composer_changed=true" >> $GITHUB_ENV
          else
            echo "composer_changed=false" >> $GITHUB_ENV
          fi

      - name: Detect migration changes
        id: check_migrations
        run: |
          if git diff --name-only HEAD^ HEAD | grep -E '^database/migrations/'; then
            echo "migrations_changed=true" >> $GITHUB_ENV
          else
            echo "migrations_changed=false" >> $GITHUB_ENV
          fi

      - name: Install dependencies (if needed)
        if: env.composer_changed == 'true'
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Generate SQL for new migrations (if needed)
        if: env.migrations_changed == 'true'
        run: |
          TIMESTAMP=$(date '+%Y-%m-%d_%H-%M-%S')
          php artisan migrate --pretend > "migrations_${TIMESTAMP}.sql"
          echo "SQL_DUMP_NAME=migrations_${TIMESTAMP}.sql" >> $GITHUB_ENV

      - name: Upload SQL dump (if generated)
        if: env.migrations_changed == 'true'
        run: |
          curl --ftp-ssl-control --ftp-pasv -T ${{ env.SQL_DUMP_NAME }} \
            --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}" \
            --connect-timeout 30 \
            --retry 3 \
            --retry-delay 5 \
            ftp://${{ secrets.FTP_HOST }}:21${{ secrets.FTP_DEPLOY_PATH }}/migrations/${{ env.SQL_DUMP_NAME }}

      - name: Upload modified files
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt
          while read file; do
            if [ -f "$file" ]; then
              curl --ftp-ssl-control --ftp-pasv -T "$file" \
                --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}" \
                --connect-timeout 30 \
                --retry 3 \
                --retry-delay 5 \
                ftp://${{ secrets.FTP_HOST }}:21${{ secrets.FTP_DEPLOY_PATH }}/"$file"
            fi
          done < changed_files.txt

      - name: Upload vendor folder (only if needed)
        if: env.composer_changed == 'true'
        run: |
          zip -r vendor.zip vendor/
          curl --ftp-ssl-control --ftp-pasv -T vendor.zip \
            --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}" \
            --connect-timeout 30 \
            --retry 3 \
            --retry-delay 5 \
            ftp://${{ secrets.FTP_HOST }}:21${{ secrets.FTP_DEPLOY_PATH }}/vendor.zip
