name: FTP Deployment Test (FTPS)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create test file with timestamp
        run: |
          echo "Hello World $(date '+%Y-%m-%d %H:%M:%S')" > test.txt

      - name: Upload file using FTPS explicit (TLS)
        run: |
          curl --ftp-ssl-control --ftp-pasv -T test.txt \
            --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}" \
            --connect-timeout 30 \
            --retry 3 \
            --retry-delay 5 \
            ftp://${{ secrets.FTP_HOST }}:21/public_html/test.txt
